name: bibi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  lottie: ^3.3.2
  dotlottie_loader: ^0.0.5
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  
  assets:
    - assets/images/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 600
        - asset: assets/fonts/DMSans_18pt-SemiBold.ttf
          weight: 700
    - family: Edu 
      fonts:
        - asset: assets/fonts/EduAUVICWANTHand-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/EduAUVICWANTHand-Bold.ttf
          weight: 900
    - family: Inter 
      fonts:
        - asset: assets/fonts/Inter.ttf
          weight: 700
           