class LanguageStrings {
  static const Map<String, String> english = {
    'hello': 'Hello',
    'im_bibi': "I'm [b]Bibi[/b]",
    'assalam_o_alaikum': 'Assalam-o-Alaikum!',
    'breast_cancer': "Breast Cancer [b]Survivor[/b]",
    'life': 'life is too beautiful to take chances',
    'life_is_too_short': 'Life is too short for bad choices',
    'skip': 'Skip',
    'next': 'Next',
    'back': 'Back',
    'get_started': 'Get Started',
    'cancer_cell' : 'What is Breast\n Cancer?',
    'family_tree' : 'Are you at risk?',
    'self_examine_card_title': 'Self Examination',
    'self_examine_subtitle': 'Understanding the basics in 3 min',
    'watch_now': 'Watch now',
    'self_examine_title': 'How to Self-Examine for Breast Cancer?',
    'how_to_treat_title': 'How to Treat?',
    'radiation': 'Radiation',
    'chemotherapy': 'Chemotherapy',
    'hormonal_tablets': 'Hormonal Tablets',
    'surgery': 'Surgery',
    'how_to_prevent_title': 'How to Prevent?',
    'drink_milk': 'Drink milk',
    'eat_protein_rich_food': 'Eat protein\nrich food',
    'increase_intake_of_vegetables': 'Increase intake\nof vegetables',
    'include_fruits_in_your_diet': 'Include fruits in\nyour diet',
    'have_plenty_of_nuts': 'Have plenty\nof nuts',
    'listen' : 'Listen',
    'help' : 'Help the patients in chores',
    'doctor': 'Consult a doctor regularly',
    'checkup' : 'Regularly get your checkup done',
    'how_to_support_title': 'How to Support?',
    'congratulations': 'Congratulations!',
    'breast_care' : 'Here\'s your daily dose of breast care!',
    'well_done_message': 'You have completed the breast cancer awareness and prevention guide. Great job learning about self-examination, treatment options, and healthy lifestyle choices!',
    'you_are_ready': 'You are ready to take charge of your health and make informed decisions.',
    'quiz_q1': 'Do you have breast cancer\nin your family?',
    'quiz_q2': 'Are you above the age of 40?',
    'quiz_q3': 'Do you smoke or drink alcohol?',
    'quiz_q4': 'Do you excercise regularly?',
    'quiz_q5': 'Is your period irregular?',
    'quiz_q6': 'Are you childless or have you had your first child after 30?'
  };

  static const Map<String, String> urdu = {
    'hello': 'اسلام علیکم',
    'im_bibi': 'میں [b]بِبی[/b] ہوں',
    'assalam_o_alaikum': 'السلام علیکم!',
    'breast_cancer': "[b]بریسٹ کینسر[/b]\nسے [b]صحتیاب[/b]\nہونے والی مریضہ",
    'life' :  '[b]زندگی[/b] [b]اتنی[/b]\n[b]خوبصورت[/b] [b]ہے[/b]\nکہ اسے خطرے میں\nنہیں ڈالا جا سکتا',
    'make_smarter_purchase_decisions': 'اپنی خریداری کو بہتر بنائیں',
    'life_is_too_short': '[b]زندگی[/b] [b]اتنی[/b]\n[b]خوبصورت[/b] [b]ہے[/b]\nکہ اسے خطرے میں\nنہیں ڈالا جا سکتا',
    'choose_wisely': 'BIBI کے ساتھ صحیح انتخاب کریں',
    'skip': 'چھوڑ دیں',
    'next': 'آگے',
    'back': 'پیچھے',
    'get_started': 'شروع کریں',
    'cancer_cell' : 'بریسٹ کینسر کیا ہے؟',
    'family_tree' : 'کیا آپ کو خطرہ ہے؟',
    'self_examine_card_title': 'خود کا معائنہ',
    'self_examine_subtitle': '3 منٹ میں بنیادی باتیں سمجھیں',
    'watch_now': 'اب دیکھیں',
    'self_examine_title': 'بریسٹ کینسر کے لیے خود کا معائنہ کیسے کریں؟',
    'how_to_treat_title': 'علاج کیسے کریں؟',
    'radiation': 'تابکاری',
    'chemotherapy': 'کیموتھیراپی',
    'hormonal_tablets': 'ہارمونل گولیاں',
    'surgery': 'سرجری',
    'how_to_prevent_title': 'بچاؤ کیسے کریں؟',
    'drink_milk': 'دودھ پیں',
    'eat_protein_rich_food': 'پروٹین سے بھرپور\nغذا کھائیں',
    'increase_intake_of_vegetables': 'سبزیوں کی مقدار\nبڑھائیں',
    'include_fruits_in_your_diet': 'اپنی خوراک میں\nپھل شامل کریں',
    'have_plenty_of_nuts': 'خوب سارے\nمیوے کھائیں',
    'listen': 'سنیں',
    'help': 'مریضوں کو کام میں مدد کریں',
    'doctor': 'باقاعدگی سے ڈاکٹر سے رجوع کریں',
    'checkup': 'باقاعدگی سے اپنی جانچ کرائیں',
    'how_to_support_title': 'کیسے مدد کریں؟',
    'continue_after_watching': 'جاری رکھیں',
    'congratulations': 'مبارک ہو!',
    'breast_care' : 'یہاں آپ کے لیے روزانہ breast care ہے!',
    'well_done_message': 'آپ نے بریسٹ کینسر سے آگاہی اور روک تھام کی رہنمائی مکمل کر لی۔ خود کے معائنے، علاج کی تدابیر اور صحت مند طرز زندگی کے انتخاب کے بارے میں سیکھنے پر شاباش!',
    'you_are_ready': 'آپ اپنی صحت پر کنٹرول رکھنے اور سوچ سمجھ کر فیصلے کرنے کے لیے تیار ہیں۔',
    'quiz_q1': 'کیا آپ کے خاندان میں\nبریسٹ کینسر که کوئی معاملہ ہے؟',
    'quiz_q2': 'کیا آپ 40 سال سے زیادہ عمر کے ہیں؟',
    'quiz_q3': 'کیا آپ سگریٹ نوشی کرتے ہیں یا شراب پیتے ہیں؟',
    'quiz_q4': 'کیا آپ باقاعدگی سے ورزش کرتے ہیں؟',
    'quiz_q5': 'کیا آپ کا حیض غیر منطقی ہے؟',
    'quiz_q6': 'کیا آپ بے اولاد ہیں یا اپنا پہلا بچہ 30 سال کے بعد پیدا کیے?'
  };

  static const Map<String, String> RomanUrdu = {
    'im_bibi': "Main [b]BIBI[/b]  hoon",
    'assalam_o_alaikum': 'Assalam-o-Alaikum!',
    'breast_cancer': "[b]Breast cancer[/b] se [b]sehatyab[/b] hone wali mariza",
    'life': '[b]Zindagi itni\n khoobsurat hai[/b]\n ke isay khatray mein \n nahi daala ja sakta',
    'cancer_cell' : 'Breast Cancer kya hai?',
    'family_tree' : 'Kya aap ko khatra hai?',
    'self_examine_card_title': 'Apne aap ka muayna',
    'self_examine_subtitle': '3 minute mein banyadi baatain samjhain',
    'watch_now': 'Ab dekhain',
    'self_examine_title': 'Breast Cancer ke liye apne aap ka muayna kaise karain?',
    'how_to_treat_title': 'Ilaj kaise karain?',
    'radiation': 'Radiation',
    'chemotherapy': 'Kemotherapy',
    'hormonal_tablets': 'Harmonal Goliyain',
    'surgery': 'Surgery',
    'how_to_prevent_title': 'Bach kaise karain?',
    'drink_milk': 'Dudh pein',
    'eat_protein_rich_food': 'Protein se bharpur\nghaza khain',
    'increase_intake_of_vegetables': 'Sabziyon ki miqdar\nbarhain',
    'include_fruits_in_your_diet': 'Apni khurak mein\nphal shamil karain',
    'have_plenty_of_nuts': 'Khoob sare\nmewe khain',
    'listen': 'Sunain',
    'breast_care' : 'Yahan aap ke liye rozana breast care hai!',

    'help': 'Merez ko kaam mein madad karain',
    'doctor': 'Baqaedaggi se doctor se rujoo karain',
    'checkup': 'Baqaedaggi se apni janch karain',
    'how_to_support_title': 'Kaise madad karain?',
    'continue_after_watching': 'Jari Rakhen',
    'congratulations': 'Mubarak ho!',
    'well_done_message': 'Aapne breast cancer se aagahi aur rok thaam ki rehnumayee maqam kar li. Apne aap ke muayna, ilaj ki tadabir aur sehat mand taraz-e-zindagi ke inthikhab ke baaray mein seekhne par shabaash!',
    'you_are_ready': 'Aap apni sehat par kontrol rakhne aur soch samjh kar faisale karne ke liye tayyar hain.',
    'quiz_q1': 'Kya aapke khandaan mein breast cancer ka koi mamla hai?',
    'quiz_q2': 'Kya aap 40 saal se zyada umar ke hain?',
    'quiz_q3': 'Kya aap cigret noshi karte hain ya sharab pite hain?',
    'quiz_q4': 'Kya aap baqaedaggi se workout karte hain?',
    'quiz_q5': 'Kya aapka haiz ghair mantaqi hai?',
    'quiz_q6': 'Kya aap bee auld hain ya apna pehla bacha 30 saal ke baad paida kie?'
  };

static String getTranslation(String language, String key) {
    if (language == 'Roman Urdu') {
      return RomanUrdu[key] ?? key;
    }

    if (language == 'اردو' || language == 'Urdu') {
      return urdu[key] ?? key;
    }

    return english[key] ?? key;
  }
}