class LanguageStrings {
  static const Map<String, String> english = {
    'hello': 'Hello',
    'im_bibi': "My name is\n [b]Bibi[/b]",
    'assalam_o_alaikum': 'Assalam-o-Alaikum!',
    'breast_cancer': "And i am a \nBreast Cancer [b]Survivor[/b]",
    'welcome': 'Welcome to the \n BIBI app',
    'life': 'life is beautiful \n and health is wealth',
    'awareness': 'I\'m here to raise \n awareness about \n breast cancer',
    'fulfill': 'Lead a healthy \n and fulfilling life',
    'skip': 'Skip',
    'next': 'Next',
    'back': 'Back',
    'hope': 'Join me on this journey',
    'get_started': 'Get Started',
    'cancer_cell': 'What is Breast\n Cancer?',
    'family_tree': 'Are you at risk?',
    'self_examine_card_title': 'How to self-examine?',
    'self_examine_subtitle': 'Understanding the basics in 3 min',
    'watch_now': 'Watch now',
    'self_examine_title': 'How to Self-Examine for Breast Cancer?',
    'how_to_treat_title': 'How to Treat?',
    'radiation': 'Radiation',
    'chemotherapy': 'Chemotherapy',
    'hormonal_tablets': 'Hormonal Tablets',
    'surgery': 'Surgery',
    'how_to_prevent_title': 'How to Prevent?',
    'drink_milk': 'Drink milk',
    'eat_protein_rich_food': 'Eat protein\nrich food',
    'increase_intake_of_vegetables': 'Increase intake\nof vegetables',
    'include_fruits_in_your_diet': 'Include fruits in\nyour diet',
    'have_plenty_of_nuts': 'Have plenty\nof nuts',
    'listen': 'Listen',
    'help': 'Help the patients in chores',
    'doctor': 'Consult a doctor regularly',
    'checkup': 'Regularly get your checkup done',
    'how_to_support_title': 'How to Support?',
    'congratulations': 'Congratulations!',
    'breast_care': 'Here\'s your daily dose of breast care!',
    'well_done_message': 'You have completed the breast cancer awareness and prevention guide. Great job learning about self-examination, treatment options, and healthy lifestyle choices!',
    'you_are_ready': 'You are ready to take charge of your health and make informed decisions.',
    'quiz_q1': 'Do you have breast cancer\nin your family?',
    'quiz_q2': 'Are you above the age of 40?',
    'quiz_q3': 'Do you smoke or drink alcohol?',
    'quiz_q4': 'Do you excercise regularly?',
    'quiz_q5': 'Is your period irregular?',
    'quiz_q6': 'Are you childless or have you had your first child after 30?',
    'what_subtitle': 'Understanding the basics in 5 min',
    'risk_subtitle': 'When an abnormality is found',
    'screening_subtitle': 'Understanding concepts of preventive screening',
    'treat_subtitle': 'Care options after detection',
    'check_subtitle': 'Tests and checks to know for sure',
    'prevent_subtitle': 'Simple steps to lower the risk',
    'support_subtitle': 'Ways to help with care and comfort',
    'good_morning': 'Good Morning, Bibi',
    'basics_tab': 'Basics',
    'care_tab': 'Care',
    'support_tab': 'Support',
    'choose_language': 'Choose Language',
    'select_language_preference': 'Select the language you prefer',
    'quiz_complete': 'Quiz completed! Retake to improve your score.',
    'questions_answered': 'questions answered',
  };

  static const Map<String, String> urdu = {
    'hello': 'اسلام علیکم',
    'im_bibi': 'میرا نام [b]بِبی[/b] ہے',
    'assalam_o_alaikum': 'السلام علیکم!',
    'breast_cancer': 'اور میں بریسٹ کینسر سے\n[b]صحتیاب[/b] ہونے والی مریضہ ہوں',
    'welcome': 'BIBI ایپ میں\nخوش آمدید',
    'life': 'زندگی خوبصورت ہے\nاور صحت ہی دولت ہے',
    'awareness': 'میں بریسٹ کینسر کے\nبارے میں آگاہی\nپھیلانے کے لیے یہاں ہوں',
    'fulfill': 'ایک صحت مند اور\nخوشحال زندگی گزاریں',
    'skip': 'چھوڑ دیں',
    'next': 'آگے',
    'back': 'پیچھے',
    'hope': 'اس سفر میں میرے\nساتھ شامل ہوں',
    'get_started': 'شروع کریں',
    'cancer_cell': 'بریسٹ کینسر کیا ہے؟',
    'family_tree': 'کیا آپ کو خطرہ ہے؟',
    'self_examine_card_title': 'خود کا معائنہ',
    'self_examine_subtitle': '3 منٹ میں بنیادی باتیں سمجھیں',
    'watch_now': 'اب دیکھیں',
    'self_examine_title': 'بریسٹ کینسر کے لیے خود کا معائنہ کیسے کریں؟',
    'how_to_treat_title': 'علاج کیسے کریں؟',
    'radiation': 'تابکاری',
    'chemotherapy': 'کیموتھیراپی',
    'hormonal_tablets': 'ہارمونل گولیاں',
    'surgery': 'سرجری',
    'how_to_prevent_title': 'بچاؤ کیسے کریں؟',
    'drink_milk': 'دودھ پیں',
    'eat_protein_rich_food': 'پروٹین سے بھرپور\nغذا کھائیں',
    'increase_intake_of_vegetables': 'سبزیوں کی مقدار\nبڑھائیں',
    'include_fruits_in_your_diet': 'اپنی خوراک میں\nپھل شامل کریں',
    'have_plenty_of_nuts': 'خوب سارے\nمیوے کھائیں',
    'listen': 'سنیں',
    'help': 'مریضوں کو کام میں مدد کریں',
    'doctor': 'باقاعدگی سے ڈاکٹر سے رجوع کریں',
    'checkup': 'باقاعدگی سے اپنی جانچ کرائیں',
    'how_to_support_title': 'کیسے مدد کریں؟',
    'continue_after_watching': 'جاری رکھیں',
    'congratulations': 'مبارک ہو!',
    'breast_care': 'یہاں آپ کے لیے روزانہ breast care ہے!',
    'well_done_message': 'آپ نے بریسٹ کینسر سے آگاہی اور روک تھام کی رہنمائی مکمل کر لی۔ خود کے معائنے، علاج کی تدابیر اور صحت مند طرز زندگی کے انتخاب کے بارے میں سیکھنے پر شاباش!',
    'you_are_ready': 'آپ اپنی صحت پر کنٹرول رکھنے اور سوچ سمجھ کر فیصلے کرنے کے لیے تیار ہیں۔',
    'quiz_q1': 'کیا آپ کے خاندان میں\nبریسٹ کینسر کا کوئی معاملہ ہے؟',
    'quiz_q2': 'کیا آپ 40 سال سے زیادہ عمر کے ہیں؟',
    'quiz_q3': 'کیا آپ سگریٹ نوشی کرتے ہیں یا شراب پیتے ہیں؟',
    'quiz_q4': 'کیا آپ باقاعدگی سے ورزش کرتے ہیں؟',
    'quiz_q5': 'کیا آپ کا حیض غیر منظم ہے؟',
    'quiz_q6': 'کیا آپ بے اولاد ہیں یا اپنا پہلا بچہ 30 سال کے بعد پیدا کیا؟',
    'what_subtitle': 'بنیادی باتیں 5 منٹ میں سمجھیں',
    'risk_subtitle': 'جب کوئی غیر معمولی بات محسوس ہو',
    'screening_subtitle': 'احتیاطی معائنے کے تصورات کو سمجھیں',
    'treat_subtitle': 'تشخیص کے بعد علاج کے اختیارات',
    'check_subtitle': 'یقین کے لیے ٹیسٹ اور جانچ',
    'prevent_subtitle': 'خطرہ کم کرنے کے آسان اقدامات',
    'support_subtitle': 'دیکھ بھال اور تسلی میں مدد کے طریقے',
    'good_morning': 'صبح بخیر، بی بی',
    'basics_tab': 'بنیادی باتیں',
    'care_tab': 'دیکھ بھال',
    'support_tab': 'معاونت',
    'choose_language': 'زبان منتخب کریں',
    'select_language_preference': 'اپنی پسند کی زبان منتخب کریں',
    'quiz_complete': 'کوئز مکمل ہوئی! اپنے سکور کو بہتر بنانے کے لیے دوبارہ کریں۔',
    'questions_answered': 'سوالات کے جوابات',
  };

  static const Map<String, String> RomanUrdu = {
    'hello': 'Salam',
    'im_bibi': 'Mera naam [b]BIBI[/b] hai',
    'assalam_o_alaikum': 'Assalam-o-Alaikum!',
    'breast_cancer': 'Aur main breast cancer \n survivor hoon',
    'welcome': 'BIBI app mein khosh aamdeed',
    'life': 'Zindagi khoobsurat hai aur sehat sab kuch hai',
    'awareness': 'Breast cancer ke baaray mein aagahi dene ain hoon',
    'fulfill': 'Ek sehatmand zindagi guzarain',
    'skip': 'Chhod dein',
    'next': 'Agay',
    'back': 'Peeche',
    'hope': 'Is safar mein\nmeray saath shamil hon',
    'get_started': 'Shuru karain',
    'cancer_cell': 'Breast Cancer kya hai?',
    'family_tree': 'Kya aap ko khatra hai?',
    'self_examine_card_title': 'khud ka muayna kaise karain?',
    'self_examine_subtitle': '3 minute mein banyadi baatain samjhain',
    'watch_now': 'Ab dekhain',
    'self_examine_title': 'Breast Cancer ke liye apne aap ka muayna kaise karain?',
    'how_to_treat_title': 'Ilaj kaise karain?',
    'radiation': 'Radiation',
    'chemotherapy': 'Kemotherapy',
    'hormonal_tablets': 'Harmonal Goliyain',
    'surgery': 'Surgery',
    'how_to_prevent_title': 'Bachawat kaise karain?',
    'drink_milk': 'Dudh pein',
    'eat_protein_rich_food': 'Protein se bharpur\nghaza khain',
    'increase_intake_of_vegetables': 'Sabziyon ki miqdar\nbarhain',
    'include_fruits_in_your_diet': 'Apni khurak mein\nphal shamil karain',
    'have_plenty_of_nuts': 'Khoob sare\nmewe khain',
    'listen': 'Sunain',
    'help': 'Merez ko kaam mein madad karain',
    'doctor': 'Baqaedaggi se doctor se rujoo karain',
    'checkup': 'Baqaedaggi se apni janch karain',
    'how_to_support_title': 'Kaise madad karain?',
    'continue_after_watching': 'Jari Rakhen',
    'congratulations': 'Mubarak ho!',
    'breast_care': 'Yahan aap ke liye rozana breast care hai!',
    'well_done_message': 'Aapne breast cancer se aagahi aur rok thaam ki rehnumayee mukammal kar li. Apne aap ke muayna, ilaj ki tadabir aur sehatmand taraz-e-zindagi ke intikhab ke baaray mein seekhne par shabaash!',
    'you_are_ready': 'Aap apni sehat par kontrol rakhne aur soch samjh kar faisale karne ke liye tayyar hain.',
    'quiz_q1': 'Kya aapke khandaan mein\nbreast cancer ka koi mamla hai?',
    'quiz_q2': 'Kya aap 40 saal se zyada umar ke hain?',
    'quiz_q3': 'Kya aap cigret noshi karte hain ya sharab pite hain?',
    'quiz_q4': 'Kya aap baqaedaggi se workout karte hain?',
    'quiz_q5': 'Kya aapka haiz ghair muntazam hai?',
    'quiz_q6': 'Kya aap be aulaad hain ya apna pehla bacha 30 saal ke baad paida kiya?',
    'what_subtitle': 'Banyadi baatain 5 minute mein samjhain',
    'risk_subtitle': 'Jab koi ghair mamuli baat mehsoos ho',
    'screening_subtitle': 'Ihtiyati muayne ke tasawwurat samjhain',
    'treat_subtitle': 'Tashkhees ke baad ilaj ke ikhtiyarat',
    'check_subtitle': 'Yaqeen ke liye test aur janch',
    'prevent_subtitle': 'Khatra kam karne ke aasaan iqdamaat',
    'support_subtitle': 'Dekh bhaal aur tasalli mein madad ke tareeqay',
    'good_morning': 'Subah Bakhair, Bibi',
    'basics_tab': 'Buniyadi Baatein',
    'care_tab': 'Dekhbhaal',
    'support_tab': 'Muaawanat',
    'choose_language': 'Zuban Muntakhib Karein',
    'select_language_preference': 'Apni Pasand Ki Zuban Muntakhib Karein',
    'quiz_complete': 'Quiz Mukammal Hui! Apne Skor Ko Behtar Banana ke liye Dobara Karein.',
    'questions_answered': 'Sawaalat ke Jawabat',
  };

  static String getTranslation(String language, String key) {
    if (language == 'Roman Urdu') {
      return RomanUrdu[key] ?? key;
    }

    if (language == 'اردو' || language == 'Urdu') {
      return urdu[key] ?? key;
    }

    return english[key] ?? key;
  }
}