// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaAUzYdOzDyAQKohxR8SPNEG_Dp_QKVrI',
    appId: '1:880423107106:web:6dc0325d9df9d4acce687b',
    messagingSenderId: '880423107106',
    projectId: 'bibi-e2d47',
    authDomain: 'bibi-e2d47.firebaseapp.com',
    storageBucket: 'bibi-e2d47.firebasestorage.app',
    measurementId: 'G-QLBKYB40S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW1R0_dEMaqA2TT20_QVMnOuwQlidMzBc',
    appId: '1:68134674517:android:626a0cb954753985a3b4dc',
    messagingSenderId: '68134674517',
    projectId: 'bibi-app-d41a0',
    storageBucket: 'bibi-app-d41a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUd91UICFJVupjApD1xfZzjSR76tmEnw',
    appId: '1:68134674517:ios:dba588d69dde73fda3b4dc',
    messagingSenderId: '68134674517',
    projectId: 'bibi-app-d41a0',
    storageBucket: 'bibi-app-d41a0.firebasestorage.app',
    iosBundleId: 'com.example.bibi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuUd91UICFJVupjApD1xfZzjSR76tmEnw',
    appId: '1:68134674517:ios:dba588d69dde73fda3b4dc',
    messagingSenderId: '68134674517',
    projectId: 'bibi-app-d41a0',
    storageBucket: 'bibi-app-d41a0.firebasestorage.app',
    iosBundleId: 'com.example.bibi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaAUzYdOzDyAQKohxR8SPNEG_Dp_QKVrI',
    appId: '1:880423107106:web:f7992b1cd129a4d6ce687b',
    messagingSenderId: '880423107106',
    projectId: 'bibi-e2d47',
    authDomain: 'bibi-e2d47.firebaseapp.com',
    storageBucket: 'bibi-e2d47.firebasestorage.app',
    measurementId: 'G-K6MQ0GHLJM',
  );

}